"""Export the validated races to a self-contained bundle for deployment.

	python -m scripts.export_race_bundle

FastF1 needs a ~600MB on-disk cache and downloads hundreds of megabytes the
first time it sees a session. That is fine on a development machine and hopeless
on a deployed instance, where it means a slow, memory-hungry first request for
every race and a hard dependency on an upstream API staying available during a
demo.

Everything the app actually serves for the five validated races is small: lap
states, pit stops, data gaps, the field's median lap, and the circuit and
pit-lane geometry come to roughly half a megabyte in total. This script writes
that out once, from the real FastF1 data, so a deployed instance can serve the
same values with no cache, no downloads, and no FastF1 import at all.

The bundle is derived data, not a substitute for the source: it is regenerated by
re-running this script, and every number in it came from the ingestion path the
tests cover.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.ingestion.fastf1_client import (  # noqa: E402
	DEFAULT_CACHE_DIR,
	SUPPORTED_RACES,
	has_verified_geometry,
	load_circuit_data,
	load_historical_session,
)

BUNDLE_DIR = Path(__file__).resolve().parents[1] / "app" / "data" / "races"


def _race_key(year: int, event: str) -> str:
	return f"{year}_{event.lower().replace(' ', '_')}"


def main() -> int:
	BUNDLE_DIR.mkdir(parents=True, exist_ok=True)
	index: list[dict[str, object]] = []

	for race in SUPPORTED_RACES:
		year, event = int(race["year"]), str(race["event"])
		key = _race_key(year, event)
		print(f"exporting {year} {event} …")

		session = load_historical_session(year, event, cache_dir=str(DEFAULT_CACHE_DIR))
		verified, note = has_verified_geometry(year, event)

		payload: dict[str, object] = {
			"year": year,
			"event": event,
			"p1_driver_code": session.p1.driver,
			"p2_driver_code": session.p2.driver,
			"p1_name": session.p1_name,
			"p1_team": session.p1_team,
			"p2_name": session.p2_name,
			"p2_team": session.p2_team,
			"total_laps": session.p1.total_laps or session.p2.total_laps,
			"p1": session.p1.model_dump(mode="json"),
			"p2": session.p2.model_dump(mode="json"),
			"historical_events": session.historical_events,
			"field_median_lap_times": session.field_median_lap_times,
			"geometry_verified": verified,
			"geometry_note": note,
		}

		if verified:
			payload["circuit"] = load_circuit_data(year, event).model_dump(mode="json")

		path = BUNDLE_DIR / f"{key}.json"
		path.write_text(json.dumps(payload, separators=(",", ":")), encoding="utf-8")
		size_kb = path.stat().st_size / 1024
		print(f"   -> {path.name}  {size_kb:.0f} KB")

		index.append(
			{
				"key": key,
				"year": year,
				"event": event,
				"race_analysis_available": True,
				"simulation_geometry_available": verified,
				"geometry_note": note,
			}
		)

	index_path = BUNDLE_DIR / "index.json"
	index_path.write_text(json.dumps(index, indent=2), encoding="utf-8")
	total = sum(path.stat().st_size for path in BUNDLE_DIR.glob("*.json")) / 1024 / 1024
	print(f"\nwrote {len(index)} races + index to {BUNDLE_DIR}  ({total:.2f} MB total)")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
